[general]
	clientID = 919252777341964288
	enabled = true
	debugging = false
	configScreen = true
	launcherIntegration = false
	version = 12

[init]
	enabled = true
	description = "Хочет зайти на сервер"
	state = "%mods% модов установлено"
	largeImageKey = "mclogo"
	largeImageText = ""
	smallImageKey = ""
	smallImageText = ""

	[[init.buttons]]
		label = "Инстаграм"
		url = "https://www.instagram.com/dima_saturday/"

[main_menu]
	enabled = true
	description = "%player% обленился"
	state = "Пялится на кнопки в меню"
	largeImageKey = "mclogo"
	largeImageText = ""
	smallImageKey = ""
	smallImageText = ""

	[[main_menu.buttons]]
		label = "Инстаграм"
		url = "https://www.instagram.com/dima_saturday/"

[server_list]
	enabled = false
	description = ""
	state = ""
	largeImageKey = ""
	largeImageText = ""
	smallImageKey = ""
	smallImageText = ""
	buttons = []

[join_game]
	enabled = true
	description = "%player% подключается к миру"
	state = "Грузится..."
	largeImageKey = "loading"
	largeImageText = "Лишь бы не вылетело!"
	smallImageKey = "mclogo"
	smallImageText = ""

	[[join_game.buttons]]
		label = "Инстаграм"
		url = "https://www.instagram.com/dima_saturday/"

[single_player]
	enabled = true
	description = "Песочница разрабротчиков"
	state = ""
	largeImageKey = "mclogo"
	largeImageText = ""
	smallImageKey = ""
	smallImageText = ""
	buttons = []

[multi_player]
	enabled = false
	description = ""
	state = ""
	largeImageKey = ""
	largeImageText = ""
	smallImageKey = ""
	smallImageText = ""
	buttons = []

[generic]
	description = "Похождения Димасика"
	state = ""
	largeImageKey = "mclogo"
	largeImageText = ""
	smallImageKey = ""
	smallImageText = ""

	[[generic.buttons]]
		label = "Инстаграм"
		url = "https://www.instagram.com/dima_saturday/"

[dimension_overrides]
	enabled = true

	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "Исследует обычный мир"
		state = ""
		largeImageKey = "overworld"
		largeImageText = "%players% players"
		smallImageKey = "mclogo"
		smallImageText = ""

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "Спустился в преисподню "
		state = ""
		largeImageKey = "nether"
		largeImageText = "%players% players"
		smallImageKey = "mclogo"
		smallImageText = ""

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "Путешествует по краю"
		state = ""
		largeImageKey = "end"
		largeImageText = "%players% players"
		smallImageKey = "mclogo"
		smallImageText = ""

	[[dimension_overrides.dimensions]]
		name = "twilightforest:twilightforest"
		description = "Ищет приключений в "
		state = "Сумеречном лесу"
		largeImageKey = "twilightforest"
		largeImageText = "%players% players"
		smallImageKey = "mclogo"
		smallImageText = ""

	[[dimension_overrides.dimensions]]
		name = "mythicbotany:alfheim"
		description = "Любуется радугой в Эльфхейме"
		state = ""
		largeImageKey = "alfheim"
		largeImageText = "%players% players"
		smallImageKey = "mclogo"
		smallImageText = ""


