
#General Config Section
[general]
	#The Client ID of the Discord App to use
	clientID = 919252777341964288
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen
	configScreen = true
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 12

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Хочет зайти на сервер"
	#The second line of text under the app name
	state = "%mods% модов установлено"
	#The Asset ID of the image to display as the large image
	largeImageKey = "mclogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "%player% обленился"
	#The seconds line of text under the app name
	state = "Пялится на кнопки в меню"
	#The Asset ID of the image to display as the large image
	largeImageKey = "mclogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = ""

	#The buttons to display on Discord
	[[main_menu.buttons]]
		label = "Инстаграм"
		url = "https://www.instagram.com/dima_saturday/"

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = false
	#The first line of text under the app name
	description = ""
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = ""
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "%player% подключается к миру"
	#The second line of text under the app name
	state = "Грузится..."
	#The Asset ID of the image to display as the large image
	largeImageKey = "loading"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Лишь бы не вылетело!"
	#The Asset ID of the image to display as the small image
	smallImageKey = "mclogo"
	#The text that gets displayed when the small image is hovered
	smallImageText = ""

	#The buttons to display on Discord
	[[join_game.buttons]]
		label = "Инстаграм"
		url = "https://www.instagram.com/dima_saturday/"

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Песочница разрабротчиков"
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = "mclogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = ""
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = ""
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = ""

	#The buttons to display on Discord
	[[multi_player.buttons]]
		label = "Инстаграм"
		url = "https://www.instagram.com/dima_saturday/"

#Fallback event for disabled events
[generic]
	#The first line of text under the app name
	description = "Похождения Димасика"
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = "mclogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = ""

	#The buttons to display on Discord
	[[generic.buttons]]
		label = "Инстаграм"
		url = "https://www.instagram.com/dima_saturday/"

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = true

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "Исследует обычный мир"
		state = ""
		largeImageKey = "overworld"
		largeImageText = ""
		smallImageKey = "mclogo"
		smallImageText = ""

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "Спустился в преисподню "
		state = ""
		largeImageKey = "nether"
		largeImageText = ""
		smallImageKey = "mclogo"
		smallImageText = ""

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "Путешествует по краю"
		state = ""
		largeImageKey = "end"
		largeImageText = ""
		smallImageKey = "mclogo"
		smallImageText = ""

	[[dimension_overrides.dimensions]]
		name = "twilightforest:twilightforest"
		description = "Ищет приключения в "
		state = "Сумеречном лесу"
		largeImageKey = "twilightforest"
		largeImageText = ""
		smallImageKey = "mclogo"
		smallImageText = ""

	[[dimension_overrides.dimensions]]
		name = "mythicbotany:alfheim"
		description = "Любуется радугой в Эльфхейме"
		state = ""
		largeImageKey = "alfheim"
		largeImageText = ""
		smallImageKey = "mclogo"
		smallImageText = ""

