onEvent('item.tags', event => {
  event.add('ct:lead_recipe_item', 'thermal:lead_ingot')
  event.add('ct:lead_recipe_item', 'thermal:lead_dust')
  event.add('ct:enderperl_recipe_item', 'minecraft:ender_pearl')
  event.add('ct:enderperl_recipe_item', 'thermal:ender_pearl_dust')
  event.add('ct:enderperl_recipe_item', 'betterendforge:ender_dust')
  event.add('ct:enderperl_recipe_item', 'appliedenergistics2:ender_dust')
  event.add('ct:enderperldust_recipe_item', 'thermal:ender_pearl_dust')
  event.add('ct:enderperldust_recipe_item', 'betterendforge:ender_dust')
  event.add('ct:enderperldust_recipe_item', 'appliedenergistics2:ender_dust')
  event.add('ct:copper_recipe_item', 'create:copper_ingot')
  event.add('ct:copper_recipe_item', 'tconstruct:copper_ingot')
  event.add('ct:copper_recipe_item', 'iceandfire:copper_ingot')
  event.add('ct:copper_recipe_item', 'thermal:copper_dust')
  event.add('ct:silver_recipe_item', 'thermal:silver_dust')
  event.add('ct:silver_recipe_item', 'thermal:silver_ingot')
  event.add('ct:silver_recipe_item', 'iceandfire:silver_ingot')
  event.add('forge:gears', 'create:cogwheel')
  })
