onEvent('block.tags', event => {
  event.add('minecraft:dragon_immune', 'betterendforge:flavolite')
  event.add('minecraft:dragon_immune', 'betterendforge:flavolite_stairs')
  event.add('minecraft:dragon_immune', 'betterendforge:flavolite_slab')
  event.add('minecraft:dragon_immune', 'betterendforge:flavolite_wall')
  event.add('minecraft:dragon_immune', 'betterendforge:thallasium_bars')
  event.add('ftbchunks:interact_whitelist', 'calemiutils:trading_post')
  event.add('twilightforest:portal/edge', 'byg:meadow_grass_block')
  event.add('twilightforest:portal/edge', 'byg:glowcelium_block')
  event.add('twilightforest:portal/edge', 'byg:peat')
  event.add('twilightforest:portal/edge', 'byg:meadow_dirt')
  event.add('twilightforest:portal/edge', 'biomesoplenty:origin_grass_block')
  event.add('twilightforest:portal/edge', 'byg:overgrown_stone')
  event.add('twilightforest:portal/edge', 'byg:overgrown_dacite')
  })