onEvent('block.tags', event => {
  event.add('minecraft:dragon_immune', 'betterendforge:flavolite')
  event.add('minecraft:dragon_immune', 'betterendforge:flavolite_stairs')
  event.add('minecraft:dragon_immune', 'betterendforge:flavolite_slab')
  event.add('minecraft:dragon_immune', 'betterendforge:flavolite_wall')
  event.add('minecraft:dragon_immune', 'betterendforge:thallasium_bars')
  event.add('ftbchunks:interact_whitelist', 'calemiutils:trading_post')
  event.add('twilightforest:portal/edge', 'byg:meadow_grass_block')
  event.add('twilightforest:portal/edge', 'byg:glowcelium_block')
  event.add('twilightforest:portal/edge', 'byg:peat')
  event.add('twilightforest:portal/edge', 'byg:meadow_dirt')
  event.add('twilightforest:portal/edge', 'biomesoplenty:origin_grass_block')
  event.add('twilightforest:portal/edge', 'byg:overgrown_stone')
  event.add('twilightforest:portal/edge', 'byg:overgrown_dacite')
  event.add('twilightforest:naga_respawn', 'ars_nouveau:mana_gem_block')
  event.add('twilightforest:lich_respawn', 'minecraft:gold_block')
  event.add('twilightforest:ghast_respawn', 'evilcraft:hardened_blood')
  event.add('twilightforest:hydra_respawn', 'tconstruct:blood_slime')
  event.add('twilightforest:qeen_respawn', 'iceandfire:dragon_ice')
  event.add('twilightforest:naga_respawn1', 'twilightforest:naga_trophy')
  event.add('twilightforest:lich_respawn1', 'twilightforest:lich_trophy')
  event.add('twilightforest:ghast_respawn1', 'twilightforest:ur_ghast_trophy')
  event.add('twilightforest:hydra_respawn1', 'twilightforest:hydra_trophy')
  event.add('twilightforest:qeen_respawn1', 'twilightforest:snow_queen_trophy')
  })